eblot/pyftdi

- pyftdi/README.rst
This PR updates the README.rst file to contain a description of the URL scheme used in connecting to `Ftdi()` objects in PyFTDI.
Since urls are the encouraged method of opening a connection, it would be useful to document this scheme in a prominent location.
Definition derived from this [issue discussion](https://github.com/eblot/pyftdi/issues/42).
> update README to describe the URL scheme

- pyftdi/i2c.py
I have an EEPROM that want's to be polled in WRITE mode, i.e. R/W set to 0.
Currently, pyftdi only allows polling in READ mode. I added an extra parameter to the poll methods, so the user can choose to poll in WRITE mode.
I set the default of this parameter to READ mode, so the change is backwards-compatible.
> Enable to poll I2C with either R/W bit 1 or 0

- pyftdi/i2c.py
This patch configures the SDA pin as input when the I2C slave puts
its N/ACK on the wire. This is so non "drive-zero" hardware (like
the 2232H) can be used to communicate with I2C devices without
hardware overhead. A current-limiting resistor on the I2C line is
still recommended (10-250 ohms, depending on your wire length and
supply voltage). This method is also used by FTDI themselves, for
example in their application note AN 411: "For the FT2232H and
FT4232H, the application includes additional GPIO writes to ADBUS
which tristate the AD1 Data Out pin when the line is not being
driven, to simulate an open-drain pin." It has also been discussed
and reported as working in Issue #46.
I'm not really a python programmer, so there's probably a more
idiomatic way to express this stuff :)
This …
> Tristate SDA pin during ACK in I2C mode for non-drive-zero devices

- pyftdi/README.rst
it seems to me like http://libusb.org/wiki/windows_backend is not so actual (last edit two years ago)
while https://github.com/libusb/libusb/wiki/Windows seems more actual
> more links and another libusb on windows link

- pyftdi/i2c.py
read() returns bytes whereas exchange() returns array. This prevents me from doing:
data = exchange()
data += read()
And it's kind of an inconsistent interface.
This commit changes the type of the return of exchange() from array to bytes.
> Return the same type for read and exchange in I2C

- pyftdi/serialext/protocol_ftdi.py
According to the pySerial API documentation, the possible values for the
timeout parameter are:
* `timeout = None`: wait forever / until requested number of bytes are
received;
* `timeout = 0`: non-blocking mode, return immediately in any case,
returning zero or more, up to the requested number of bytes;
* `timeout = x`: set timeout to x seconds (float allowed) returns
immediately when the requested number of bytes are available,
otherwise wait until the timeout expires and return all bytes that
were received until then.
The FtdiSerial class did not comply with this specification, as it
treated timeout = 0 as wait forever, and crashes when timeout is None.
> serialext: Fix timeout interpretation

- pyftdi/serialext/protocol_ftdi.py
FtdiSerial.read() would always sleep for 10ms at each loop iteration,
even when all requested data has been retrieved.  Hence, small reads are
penalized, even though they should be competitive with larger reads
thanks to the read buffer inside the Ftdi device object.
This patch provides a quick exit path in FtdiSerial.read() as soon as
all requested data is read.
> serialext: Do not sleep when all requested data is read

- pyftdi/serialext/protocol_ftdi.py
This makes write() compatible with write() from pySerial.
> serialext: Return num bytes written in write()

- pyftdi/ftdi.py
- pyftdi/usbtools.py
These two patches allows pyftdi to work together with OS drivers: 
* detach only the kernel drivers on a per interface (FTDI port) basis to allow some ports being used by the host and some by pyftdi
* reattach kernel drivers when we are done with the interface to allow the host driver accessing the port when pyftdi is done
Tested on Linux only.
> Fix busy ports

- setup.cfg
fixes the following error on 'pip install':
```
error: [Errno 2] No such file or directory: 'pyftdi/LICENSE'
Failed building wheel
```
> packaging: fix license file path in setup

- pyftdi/ftdi.py
The current frequency calculation has some issues which are fixed by this pull request:
- When desired frequency is below base frequency (6 MHz), high speed clock mode (30 Mhz) is always disabled, leading to coarse frequency selection and inability to select frequencies like: 5 MHz, 4.3 MHz, 2.5 MHz etc.. The proposed change will select the optimal clock mode and divisor to minimize the percentile error from the desired frequency.
- Formula for divisor will now round to nearest instead of always rounding up.
- Divisor can no longer overflow 0xFFFF for extremely low frequencies (below ~92 Hz).
- Calculation of actual_freq corrected to be according to FTDI AN135 (minor).
> ftdi: Fix divisor calculation for _set_frequency()

- pyftdi/doc/tools.rst
One byte change I noticed while reading the docs.
> Fix typo in tools documentation.

- pyftdi/i2c.py
Delay the SCL transition to correctly catch the SDA low->high transition.
> Fix #205 - I2C stop violation

- pyftdi/ftdi.py
- pyftdi/jtag.py
- pyftdi/tests/jtag.py
This provides an updated API to allow proper simultaneous shifting in/out of data. I'm not sure how useful the `shift_register` function is. The new `shift_and_update_register` is what I use, and there are two new tests for it.
Let me know if you have any suggestions/issues.
> Fix for issue #194

- pyftdi/bin/pyterm.py
- pyftdi/bin/pyterm_winkeys.py
Reverses commit fa951f8f82c5d03c81cdc7d106288efee4f9515e
Provides actual support for "fullmode" and normal mode in Windows
Changes:
- workaround using subprocess module to force terminal to process ANSI escape sequences
- windows keyboard scan code to escape sequence dictionary
msvcrt.getch() gathers raw keyboard codes for function keys, unprocessed by kernel
- cleanup of if statements
Tested with:
Windows 10
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
a router at default baud rate
Signed-off-by: Michael Pratt <mpratt51@gmail.com>
> UART: pyterm.py: Full functionality for Windows

- pyftdi/jtag.py
This PR is a couple of small fixes.  First, ensure sync() is called when calling read_from_buffer().  Second, fix the definition of shift_register to accept the bits to be shifted out.  Third, add some sanity checking to shift_register to check that the lengths match.
> Various JTAG fixes

- pyftdi/doc/troubleshooting.rst
Adds a potential solution for the "No backend available" error on windows when using pyinstaller.
Issue discussed further in https://github.com/eblot/pyftdi/issues/29
> Update troubleshooting doc

- pyftdi/jtag.py
If write_tms() syncs without regard to should_read, the minimum period between writes to JTAG registers (e.g. the EXTEST register) is bounded by the round-trip USB delay. If write_tms() only syncs when the read data is required (i.e. should_read is true), then back to back writes to JTAG registers can occur at the full TCLK rate.
This is particularly important when external signals need to be precisely sequenced with JTAG commands (for example, applying an external programming voltage for blowing an eFuse).
Example before this change (programming voltage is applied for 3ms, when it only needs to be applied for 40us).  The total lifetime voltage application for an eFuse block is ~10ms, so this expends almost a third of that budget for blowing eFuses on a device, when it only needs to …
> jtag: write_tms() should only sync() if should_read is true

- pyftdi/i2c.py
set lines to high-z after epilog when fake-tristate is enabled
Similiar to issue #46, FT2232H/FT4232H never *really* relax the bus
after the epilog, because they don't support tristate in hardware. This
leads to blocking the bus when another master (besides the FTDI) is
present.
Implement fake-tristate for both SCL and SDA after the epilog to unblock
the bus.
Signed-off-by: Michael Niewöhner <foss@mniewoehner.de>
> i2c: relax the bus after epilog in fake-tristate mode

- pyftdi/eeprom.py
In eeprom.py:721 the calculation of the address where the CRC is stored in the EEPROM is fixed to be at either `0x9E` or `eeprom._size-2`. Without this fix the last two bytes of the `serial` string can be overwritten by the CRC without raising the exception `FtdiEepromError(...)` inline 725.
> Fix start address of CRC word (16 bit) when checking the remaining space for USB descriptor strings

- pyftdi/gpio.py
- pyftdi/i2c.py
After the master sends the request to read from a slave and after the ACK from the slave, the _send_check_ack function ends with SDA being a HI output. During this period to when the master starts clocking in the data it wants to read, some slaves pull the SDA line low. This would short the SDA output to GND, causing it to draw its max current (16mA for the FT4232). This fix makes it so that if the next action after the ACK is a read, SDA remains as an input during this period of time.
> Fake tri-state: Move SDA=output after ACK to before I2C write to avoid momentary shorts after ACK during I2C reads

- pyftdi/i2c.py
Minor docstring fix and clarification for I2c
Mostly wanted to fix read/write. The other change is mostly a suggestion and I don't mind either way.
> Documentation fix of i2c docstrings

- pyftdi/eeprom.py
Hi!
Please check this patch that contains two commits.
1. The first commit fixes a bug with incorrect memory offset computation when setting 'config' bits in EEPROM (or, to be precise, when clearing them). Those include e.g. `remote_wakeup`, `self_powered`, `suspend_pull_down`, etc.
2. The second commit adds a couple of missing functionalities: it allows to set & write `channel_*_type`, `channel_*_driver`, `suspend_dbus7` and `chip` into EEPROM for FT2232H chip. I've also tried to support FT232H but I haven't tested that one.
The reason why I'd like to have these functionalities is to be able to create an EEPROM image for a blank FT2232H from scratch using only pyftdi, without help from proprietary FTDI tools or C libftdi.
> eeprom: bugfix & some improvements for ft232h / ft2232h

- pyftdi/tests/toolsimport.py
- pyftdi/tests/uart.py
```
ImportError while importing test module '…/pyftdi/pyftdi/tests/toolsimport.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
…/lib/python3.13/importlib/__init__.py:88: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
pyftdi/tests/toolsimport.py:16: in <module>
from unittest import TestCase, TestSuite, makeSuite, main as ut_main
E   ImportError: cannot import name 'makeSuite' from 'unittest' (…/lib/python3.13/unittest/__init__.py)
```
https://github.com/python/cpython/issues/104835
https://github.com/python/cpython/pull/104836
https://github.com/python/cpython/commit/b1cb30ec8639e4e65f62e8f6cd44e979640431c8
https://docs.python.org/3/whatsnew/3.13.html#unittest
@eblot
> tests: Fix for Python 3.13 (unittest.makeSuite was removed)

- pyftdi/doc/authors.rst
- pyftdi/eeprom.py
When the type isn't set in the eeprom determine it from the device version instead.
> eeprom: Fall back to device version of type not set in eeprom

- pyftdi/bin/ftconf.py
This commit fixes a bug in ftconf.py where the eeprom device was not closed before exiting.  This meant the kernel driver was not re-attached causing device disconnection.
> bugfix(eeprom): make sure to close eeprom #394

- pyftdi/i2c.py
Avoids accidential start conditions, fixes #405
> i2c: glitch high rather than low when tristating SCL+SDA

- pyftdi/doc/api/spi.rst
Fixes #406 
Correct a small mistake in the SPI API documentation. 
Make the set_direction call clearer to readers by adding the parameter names to the function call, and using binary so it is clear which pin position the bits correspond to.
> Correct mistake in SPI API documentation example
